#!/bin/bash

set -e

# Setup configuration files
./script/event-triggers-ddl-watcher-config/test-bootstrap-event-triggers

# Execute data transformation tests
./script/test-e2e-after-bootstrap postgres
