#!/bin/bash

# Die on any error
set -e

docker-compose up -d postgres

# Run golang tests
docker-compose run --rm test

./script/event-triggers-ddl-watcher-config/test-e2e-legacy
./script/legacy-ddl-watcher-config/test-e2e-event-triggers
